server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/cesizenV2?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true